seeder_task:
  description: >
    Your goal is to draft an original, human-like, and curiosity-driven post or question for {topic}.
    
    **Steps:**
    1. Use web search tool to research current trends, common challenges, and popular discussion points related to {topic}.
    2. Based on your research, brainstorm 3-5 unique, open-ended questions or discussion starters that are genuinely curiosity-driven and not overtly promotional. Aim for concise and clear phrasing.
    3. Select the best question/discussion starter that you believe will spark the most authentic conversation.
    4.  Draft the full Reddit post, including a compelling title and a body that encourages replies.

    **Example of human-like post or question:**
    1. How do you stay motivated to cold call 50+ leads in a day without burning out?
    2. What is the hardest part about wholesaling for you: finding leads or closing them?
    3. Have you ever found a way to make cold calling feel less robotic?
    4. What systems or hacks do you use to qualify leads faster when wholesaling?
  expected_output: >
    10 Posts or questions of the most relevant information about {topic}.
  agent: seeder_agent